### ISSUE TITLE
README suggests that Cest cannot be used for C projects

### ISSUE THREAD

**Issue by guyikcgg** [cegonse/cest#78]
In the README, it can be read:
```A test-driven development framework for C++ inspired by Jest and similar frameworks.```
However, you can also use Cest to test software written in C. We may want to change the description to something like:
```A test-driven development framework for C and C++ inspired by Jest and similar frameworks.```

Later on, we may want to clarify that Cest is written in C++ or that tests will be written in C++. 

Otherwise, C programmers won't even realize that Cest is a great tool to test and perform TDD on C projects. For clarity, we may want to translate the existing getting-started example to C.

**Comment by cegonse** [comment]
Thanks for the issue! This has been fixed in the README. Also, the website documentation now contains a guide on how to integrate Cest with C: https://cestframework.com/quickstart/bare_c/
